apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs
      containers:
        - name: app
          image: oratar333/catalog_shop:31
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: "/depend/logging"
              name: nfs-volume

