apiVersion: v1
kind: Service
metadata:
  name: service-app 
  labels:
    name: app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      name: http
  selector:
    name: app
