apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: prod 
  labels:
    app: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      volumes:
        - name: log
          hostPath:
            path: /log/app
            type: DirectoryOrCreate
      containers:
        - name: app
          image: oratar333/catalog_shop:31
          ports:
            - containerPort: 5000
          volumeMounts:
            - mountPath: /depend/logging
              name: log

