apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sec
spec:
  storageClassName: nfs
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs_share
    server: 52.194.225.19

